### ISSUE TITLE
sync-profile md interval data type example error

### ISSUE THREAD

**Issue by mfzhsn** [sdcio/docs#64]
Sync-profile example md needs to be updated for interval

Error Logs:
```
[root@sros sdc-sros-controller]# kubectl apply -f sync-profile.yml
The TargetSyncProfile "netconf-getconfig" is invalid:
* spec.sync[0].interval: Invalid value: "integer": spec.sync[0].interval in body must be of type string: "integer"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```

Fix:

```
apiVersion: inv.sdcio.dev/v1alpha1
kind: TargetSyncProfile
metadata:
  name: netconf-getconfig
  namespace: default
spec:
  buffer: 0
  workers: 10
  validate: true
  sync:
  - name: config
    protocol: netconf
    paths:
    - /
    mode: sample
    encoding: config
    interval: "10"
```
